server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://121.43.183.238:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://113.16.255.12:11028/nanningfemale?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lh18178007095
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

c-sleeve-backend:
  security:
    jwt-key: 7777712312312
    token-expired-in: 36400000