server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://121.43.183.238:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lh18178007095
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    host: 121.43.183.238
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired
    timeout: 5000

rocketmq:
  producer:
    producer-group: SleeveProducerGroup
  consumer:
    consumer-group: SleeveConsumerGroup
  namesrv-addr: 121.43.183.238.:9876
  delay-level: 3

c-sleeve-backend:
  security:
    jwt-key: 7777712312312
    token-expired-in: 36400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    wx:
      pay-callback-host: http://sleeve.vaiwan.com
      pay-callback-path: /v1/payment/wx/notify