server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://121.43.183.238:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lh18178007095
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
