spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

c-sleeve-backend:
  api-package: com.sheildog.csleevebackend.api