spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

c-sleeve-backend:
  api-package: com.sheildog.csleevebackend.api
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L

wx:
  appid: wx9908fbab69fc1b3d
  appsecret: 248dcbf670f6dd56c8f81b79fbe39d44
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code